/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pianoFrame;

import jaco.mp3.player.MP3Player;
import java.awt.Color;
import  java.io.*;
/**
 *
 * @author Lenovo
 */
public class pianoFrame extends javax.swing.JFrame {

    /**
     * Creates new form pianoFrame
     */
    public pianoFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DS1 = new javax.swing.JButton();
        FS1 = new javax.swing.JButton();
        GS1 = new javax.swing.JButton();
        AS1 = new javax.swing.JButton();
        CS2 = new javax.swing.JButton();
        DS2 = new javax.swing.JButton();
        FS2 = new javax.swing.JButton();
        GS2 = new javax.swing.JButton();
        CS3 = new javax.swing.JButton();
        DS3 = new javax.swing.JButton();
        FS3 = new javax.swing.JButton();
        GS3 = new javax.swing.JButton();
        AS3 = new javax.swing.JButton();
        AS2 = new javax.swing.JButton();
        CS1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akash's Piano");
        setMinimumSize(new java.awt.Dimension(1800, 700));
        getContentPane().setLayout(null);

        DS1.setBackground(new java.awt.Color(0, 0, 0));
        DS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DS1.setForeground(new java.awt.Color(255, 255, 255));
        DS1.setText("D#");
        DS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DS1ActionPerformed(evt);
            }
        });
        getContentPane().add(DS1);
        DS1.setBounds(150, 20, 50, 250);

        FS1.setBackground(new java.awt.Color(0, 0, 0));
        FS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FS1.setForeground(new java.awt.Color(255, 255, 255));
        FS1.setText("F#");
        FS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FS1ActionPerformed(evt);
            }
        });
        getContentPane().add(FS1);
        FS1.setBounds(310, 20, 50, 250);

        GS1.setBackground(new java.awt.Color(0, 0, 0));
        GS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GS1.setForeground(new java.awt.Color(255, 255, 255));
        GS1.setText("G#");
        GS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GS1ActionPerformed(evt);
            }
        });
        getContentPane().add(GS1);
        GS1.setBounds(390, 20, 50, 250);

        AS1.setBackground(new java.awt.Color(0, 0, 0));
        AS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AS1.setForeground(new java.awt.Color(255, 255, 255));
        AS1.setText("A#");
        AS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AS1ActionPerformed(evt);
            }
        });
        getContentPane().add(AS1);
        AS1.setBounds(470, 20, 50, 250);

        CS2.setBackground(new java.awt.Color(0, 0, 0));
        CS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CS2.setForeground(new java.awt.Color(255, 255, 255));
        CS2.setMnemonic('1');
        CS2.setText("C#");
        CS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS2ActionPerformed(evt);
            }
        });
        getContentPane().add(CS2);
        CS2.setBounds(640, 20, 50, 250);

        DS2.setBackground(new java.awt.Color(0, 0, 0));
        DS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DS2.setForeground(new java.awt.Color(255, 255, 255));
        DS2.setMnemonic('2');
        DS2.setText("D#");
        DS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DS2ActionPerformed(evt);
            }
        });
        getContentPane().add(DS2);
        DS2.setBounds(720, 20, 50, 250);

        FS2.setBackground(new java.awt.Color(0, 0, 0));
        FS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FS2.setForeground(new java.awt.Color(255, 255, 255));
        FS2.setMnemonic('4');
        FS2.setText("F#");
        FS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FS2ActionPerformed(evt);
            }
        });
        getContentPane().add(FS2);
        FS2.setBounds(870, 20, 50, 250);

        GS2.setBackground(new java.awt.Color(0, 0, 0));
        GS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GS2.setForeground(new java.awt.Color(255, 255, 255));
        GS2.setMnemonic('5');
        GS2.setText("G#");
        GS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GS2ActionPerformed(evt);
            }
        });
        getContentPane().add(GS2);
        GS2.setBounds(950, 20, 50, 250);

        CS3.setBackground(new java.awt.Color(0, 0, 0));
        CS3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CS3.setForeground(new java.awt.Color(255, 255, 255));
        CS3.setMnemonic('6');
        CS3.setText("C#");
        CS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS3ActionPerformed(evt);
            }
        });
        getContentPane().add(CS3);
        CS3.setBounds(1180, 20, 50, 250);

        DS3.setBackground(new java.awt.Color(0, 0, 0));
        DS3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DS3.setForeground(new java.awt.Color(255, 255, 255));
        DS3.setMnemonic('7');
        DS3.setText("D#");
        DS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DS3ActionPerformed(evt);
            }
        });
        getContentPane().add(DS3);
        DS3.setBounds(1260, 20, 50, 250);

        FS3.setBackground(new java.awt.Color(0, 0, 0));
        FS3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FS3.setForeground(new java.awt.Color(255, 255, 255));
        FS3.setMnemonic('9');
        FS3.setText("F#");
        FS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FS3ActionPerformed(evt);
            }
        });
        getContentPane().add(FS3);
        FS3.setBounds(1410, 20, 50, 250);

        GS3.setBackground(new java.awt.Color(0, 0, 0));
        GS3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GS3.setForeground(new java.awt.Color(255, 255, 255));
        GS3.setMnemonic('0');
        GS3.setText("G#");
        GS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GS3ActionPerformed(evt);
            }
        });
        getContentPane().add(GS3);
        GS3.setBounds(1490, 20, 50, 250);

        AS3.setBackground(new java.awt.Color(0, 0, 0));
        AS3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AS3.setForeground(new java.awt.Color(255, 255, 255));
        AS3.setText("A#");
        AS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AS3ActionPerformed(evt);
            }
        });
        getContentPane().add(AS3);
        AS3.setBounds(1570, 20, 50, 250);

        AS2.setBackground(new java.awt.Color(0, 0, 0));
        AS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AS2.setForeground(new java.awt.Color(255, 255, 255));
        AS2.setText("A#");
        AS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AS2ActionPerformed(evt);
            }
        });
        getContentPane().add(AS2);
        AS2.setBounds(1030, 20, 50, 250);

        CS1.setBackground(new java.awt.Color(0, 0, 0));
        CS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CS1.setForeground(new java.awt.Color(255, 255, 255));
        CS1.setText("C#");
        CS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CS1ActionPerformed(evt);
            }
        });
        getContentPane().add(CS1);
        CS1.setBounds(70, 20, 50, 250);

        E1.setBackground(new java.awt.Color(255, 255, 255));
        E1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        E1.setMnemonic('e');
        E1.setText("E");
        E1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        getContentPane().add(E1);
        E1.setBounds(180, 20, 79, 550);

        D1.setBackground(new java.awt.Color(255, 255, 255));
        D1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        D1.setText("D");
        D1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        getContentPane().add(D1);
        D1.setBounds(100, 20, 89, 550);

        F1.setBackground(new java.awt.Color(255, 255, 255));
        F1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        F1.setText("F");
        F1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        getContentPane().add(F1);
        F1.setBounds(260, 20, 75, 550);

        G1.setBackground(new java.awt.Color(255, 255, 255));
        G1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        G1.setText("G");
        G1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });
        getContentPane().add(G1);
        G1.setBounds(330, 20, 87, 550);

        A1.setBackground(new java.awt.Color(255, 255, 255));
        A1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        A1.setMnemonic('t');
        A1.setText("A");
        A1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        getContentPane().add(A1);
        A1.setBounds(410, 20, 83, 550);

        C2.setBackground(new java.awt.Color(255, 255, 255));
        C2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        C2.setText("C");
        C2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        getContentPane().add(C2);
        C2.setBounds(570, 20, 81, 550);

        D2.setBackground(new java.awt.Color(255, 255, 255));
        D2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        D2.setText("D");
        D2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        getContentPane().add(D2);
        D2.setBounds(650, 20, 89, 550);

        E2.setBackground(new java.awt.Color(255, 255, 255));
        E2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        E2.setMnemonic('s');
        E2.setText("E");
        E2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        getContentPane().add(E2);
        E2.setBounds(730, 20, 79, 550);

        F2.setBackground(new java.awt.Color(255, 255, 255));
        F2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        F2.setText("F");
        F2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        getContentPane().add(F2);
        F2.setBounds(810, 20, 75, 550);

        G2.setBackground(new java.awt.Color(255, 255, 255));
        G2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        G2.setText("G");
        G2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });
        getContentPane().add(G2);
        G2.setBounds(880, 20, 87, 550);

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        A2.setMnemonic('f');
        A2.setText("A");
        A2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        getContentPane().add(A2);
        A2.setBounds(960, 20, 83, 550);

        C1.setBackground(new java.awt.Color(255, 255, 255));
        C1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        C1.setText("C");
        C1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1);
        C1.setBounds(20, 20, 81, 550);

        C3.setBackground(new java.awt.Color(255, 255, 255));
        C3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        C3.setText("C");
        C3.setToolTipText("");
        C3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        getContentPane().add(C3);
        C3.setBounds(1120, 20, 81, 550);

        D3.setBackground(new java.awt.Color(255, 255, 255));
        D3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        D3.setText("D");
        D3.setToolTipText("");
        D3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        getContentPane().add(D3);
        D3.setBounds(1200, 20, 89, 550);

        E3.setBackground(new java.awt.Color(255, 255, 255));
        E3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        E3.setMnemonic('j');
        E3.setText("E");
        E3.setToolTipText("");
        E3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        getContentPane().add(E3);
        E3.setBounds(1280, 20, 79, 550);

        F3.setBackground(new java.awt.Color(255, 255, 255));
        F3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        F3.setText("F");
        F3.setToolTipText("");
        F3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        getContentPane().add(F3);
        F3.setBounds(1360, 20, 75, 550);

        G3.setBackground(new java.awt.Color(255, 255, 255));
        G3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        G3.setText("G");
        G3.setToolTipText("");
        G3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });
        getContentPane().add(G3);
        G3.setBounds(1430, 20, 87, 550);

        A3.setBackground(new java.awt.Color(255, 255, 255));
        A3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        A3.setMnemonic('l');
        A3.setText("A");
        A3.setToolTipText("");
        A3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        getContentPane().add(A3);
        A3.setBounds(1510, 20, 83, 550);

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        B3.setMnemonic(';');
        B3.setText("B");
        B3.setToolTipText("");
        B3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        getContentPane().add(B3);
        B3.setBounds(1590, 20, 83, 550);

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        B1.setMnemonic('y');
        B1.setText("B");
        B1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(490, 20, 83, 550);

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setFont(new java.awt.Font("Tahoma", 1, 74)); // NOI18N
        B2.setMnemonic('g');
        B2.setText("B");
        B2.setToolTipText("");
        B2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(1040, 20, 83, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
            String path = "D:\\piano sounds\\C3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_C1ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
String path = "D:\\piano sounds\\D3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_D1ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
            String path = "D:\\piano sounds\\E3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();        // TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
     String path = "D:\\piano sounds\\F3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_F1ActionPerformed

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed
       String path = "D:\\piano sounds\\G3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_G1ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
       String path = "D:\\piano sounds\\A3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        String path = "D:\\piano sounds\\B3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_B1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        String path = "D:\\piano sounds\\C4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_C2ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
       String path = "D:\\piano sounds\\D4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_D2ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
      String path = "D:\\piano sounds\\E4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_E2ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        String path = "D:\\piano sounds\\F4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_F2ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed
            String path = "D:\\piano sounds\\G4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_G2ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        String path = "D:\\piano sounds\\A4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_A2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
       String path = "D:\\piano sounds\\B4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_B2ActionPerformed

    private void CS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS1ActionPerformed
        String path = "D:\\piano sounds\\Db3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_CS1ActionPerformed

    private void DS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DS1ActionPerformed
        String path = "D:\\piano sounds\\Eb3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_DS1ActionPerformed

    private void FS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FS1ActionPerformed
       String path = "D:\\piano sounds\\Gb3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_FS1ActionPerformed

    private void GS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GS1ActionPerformed
       String path = "D:\\piano sounds\\Ab3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_GS1ActionPerformed

    private void AS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AS1ActionPerformed
       String path = "D:\\piano sounds\\Bb3.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_AS1ActionPerformed

    private void CS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS2ActionPerformed
            String path = "D:\\piano sounds\\Db4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_CS2ActionPerformed

    private void DS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DS2ActionPerformed
       String path = "D:\\piano sounds\\Eb4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_DS2ActionPerformed

    private void FS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FS2ActionPerformed
        String path = "D:\\piano sounds\\Gb4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_FS2ActionPerformed

    private void GS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GS2ActionPerformed
        String path = "D:\\piano sounds\\Ab4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_GS2ActionPerformed

    private void AS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AS2ActionPerformed
            String path = "D:\\piano sounds\\Bb4.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_AS2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
     String path = "D:\\piano sounds\\C5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_C3ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
    String path = "D:\\piano sounds\\D5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_D3ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
       String path = "D:\\piano sounds\\E5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_E3ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
       String path = "D:\\piano sounds\\F5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_F3ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
    String path = "D:\\piano sounds\\G5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_G3ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
       String path = "D:\\piano sounds\\A5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_A3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
      String path = "D:\\piano sounds\\B5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_B3ActionPerformed

    private void CS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CS3ActionPerformed
             String path = "D:\\piano sounds\\Db5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_CS3ActionPerformed

    private void DS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DS3ActionPerformed
            String path = "D:\\piano sounds\\Eb5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_DS3ActionPerformed

    private void FS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FS3ActionPerformed
            String path = "D:\\piano sounds\\Gb5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_FS3ActionPerformed

    private void GS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GS3ActionPerformed
            String path = "D:\\piano sounds\\Ab5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_GS3ActionPerformed

    private void AS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AS3ActionPerformed
            String path = "D:\\piano sounds\\Bb5.mp3";
            MP3Player mp3player = new MP3Player(new File(path));
            mp3player.play();
    }//GEN-LAST:event_AS3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pianoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton AS1;
    private javax.swing.JButton AS2;
    private javax.swing.JButton AS3;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton CS1;
    private javax.swing.JButton CS2;
    private javax.swing.JButton CS3;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton DS1;
    private javax.swing.JButton DS2;
    private javax.swing.JButton DS3;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton FS1;
    private javax.swing.JButton FS2;
    private javax.swing.JButton FS3;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton GS1;
    private javax.swing.JButton GS2;
    private javax.swing.JButton GS3;
    // End of variables declaration//GEN-END:variables
}
